<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Traits\HasExpenses;
use App\Traits\HasPayrolls;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory, HasExpenses, HasPayrolls, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'phone_number',
        'idnumber',
        'department',
        'job_title',
        'hire_date',
        'salary',
        'employment_status',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'hire_date' => 'date',
        'salary' => 'decimal:2',
        'employment_status' => 'string',
    ];

    /**
     * Get the expenses associated with the employee.
     */
    public function expenses()
    {
        return $this->hasMany(Expense::class);
    }

    /**
     * Get the meter readings associated with the employee.
     */
    public function meterReadings()
    {
        return $this->hasMany(MeterReading::class);
    }

    /**
     * Get the payroll records associated with the employee.
     */
    public function payrolls()
    {
        return $this->hasMany(Payroll::class);
    }

    /**
     * Get the reports generated by the employee.
     */
    public function reports()
    {
        return $this->hasMany(Report::class, 'generated_by');
    }
}
